### ISSUE TITLE
get_history method is returning an empty dataframe

### ISSUE THREAD

**Issue by sharanyagantla** [swapniljariwala/nsepy#21]
from nsepy import get_history, get_index_pe_history
from datetime import date
I am using python 3.6 version and when i am trying to use this method
df1 = nsepy.get_history("AARVEEDEN", date(2006,11,21), date(2016,12,5))

its returning an empty dataframe
Please help me solve this error.

**Comment by swapniljariwala** [comment]
Please pull from master on repository and run install library, This issue has been resolved in #17

**Comment by swapniljariwala** [comment]
alternately uninstall nsepy and install again please

**Comment by Ameerpappay** [comment]
Iam still getting this issue.
tried uninstall nsepy and reinstall again but didnt resolved.
Is there any limit for the requests we can make in a day?
I have done around 30 requests only
